version: '3.5'

services:

  frontend:
    image: martendocker/three-tier-app-ubuntu-frontend:latest
    command: ["ping", "database"]

  database:
    image: martendocker/three-tier-app-ubuntu-database:latest
    command: ["ping", "localhost"]
    
  worker:
    image: martendocker/three-tier-app-ubuntu-worker:latest
    command: ["ping", "database"]
    
