version: '3.5'

services:

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
      
  database:
    build: ./database
    image: three-tier-app-ubuntu-database:latest
    command:
      - "ping 127.0.0.1"
    
  worker:
    build: ./worker
    image: three-tier-app-ubuntu-worker:latest
    command:
      - "ping database"
    
